#!/usr/bin/perl

############# Parameters Setting ###############
my $nloci=4;                  # number of loci in input file
my $mu=2e-8;                  # mutation rate per base pair
my $int=1;                   # number of steps between simulated steps
my $addburnin=0;              # number of lines to ignore for burnin
my $inputfile="inputmimar";   # input file name
my $outfile="outputgof2";     # output file name
my $post_dist="outputmimar2"; # name of the standard output file from MIMAR (i.e., with the estimated posterior distributions)

#### NOTE: The commande line for gof below is for a *simple* Isolation-Migration model and has no recombination
#### - Needs to add switch -r to include recombination and any other switches used for MIMAR analysis if the model was more complex.
my $extra_switches="";

########### End of parameters and option seting ############

open (FILEIN, $post_dist)|| die "Can't open FILEIN: $post_dist!\n";
my $sent=$_;
chomp($sent);   	
my @temp=split(/\t/,$sent);
my $count=0;
while($count<12+$addburnin)   # Loop to avoid the begining of MIMAR output file
{
    $sent = readline FILEIN;
    chomp($sent); 
    @temp=split(/\t/,$sent);
    $count++;
}
$count=1;          # number of sets of parameters analyzed
my $nparam=$int-1; # initialization for interval between steps 
 while(<FILEIN>)   # Loop along MIMAR output file
 { 
     $sent=$_;     # New line
     $nparam++ ;
     if($nparam==$int)
     {     
         chomp($sent);   
         my @temp=split(/\t/,$sent);
         
         if($count==1)              # Initial simulation
         {
             open (FILE, ">$outfile")|| die "Can't open FILEIN: $outfile!\n";
             print FILE "Sim#\tStep#\tS1\tS2\tSs\tSf\tFst\tpi1\tpi2\tD1\tD2\n";
             print FILE "$count\t$temp[0]\t";
             close FILE;
         }
         else                      # following simulations
         {
             open (FILE, ">>$outfile")|| die "Can't open FILEIN: $outfile!\n";
             print FILE "$count\t$temp[0]\t";
             close FILE;           
         }
          system("./mimargof $nloci -lf $inputfile -u $mu -t $temp[1] -ej $temp[4] -N $temp[5] -n $temp[2] -m 1 2 $temp[6] -m 2 1 $temp[7] $extra_switches >>$outfile");
         $count+=1;
         $nparam=0;
     }   
}
close(FILEIN);

