####################################
##### Processing
####################################
Gender[which(Gender[,2]==1),2]='M';
Gender[which(Gender[,2]==2),2]='F';
Race[which(Race[,2]==1),2]='2Hisp';
Race[which(Race[,2]==2),2]='2Hisp';
Race[which(Race[,2]==3),2]='1NHWhite';
Race[which(Race[,2]==4),2]='3NHBlack';
Race[which(Race[,2]==5),2]='4Other';
BMICL=BMIC;
BMICL[which(BMICL[,2]<24),2]=24;
BMICL[which(BMICL[,2]>35),2]=35;
BMI=BMIC;
BMI[which(BMIC[,2]<18.5),2]='2Underweight';
BMI[which(BMIC[,2]>=18.5&BMIC[,2]<25),2]='1Normal';
BMI[which(BMIC[,2]>=25&BMIC[,2]<30),2]='3Overweight';
BMI[which(BMIC[,2]>=30),2]='4Obese';
TCH[,2]=as.numeric(TCH[,2]);
TCHL=TCH;
TCHL[which(TCH[,2]<200),2]='1Normal';
TCHL[which(TCH[,2]>=200&TCH[,2]<240),2]='2High';
TCHL[which(TCH[,2]>=240),2]='3VeryHigh';
THDL[,2]=as.numeric(THDL[,2]);
THDL_L=THDL;
THDL_L[which(THDL[,2]>=40),2]='1Normal';
THDL_L[which(THDL[,2]<40),2]='2Low';
T2D[which(T2D[,2]>2),2]='.';
T2D[which(T2D[,2]==2),2]=0;
#################################
#Matching
#################################
loc=match(Data$SEQN,Age[,1]);
Data$Age=as.factor(round(Age[loc,2]/10));
loc=match(Data$SEQN,Age[,1]);
Data$AgeC=as.numeric(Age[loc,2]);
loc=match(Data$SEQN,Gender[,1]);
Data$Gender=as.factor(Gender[loc,2]);
loc=match(Data$SEQN,Race[,1]);
Data$Race=as.factor(Race[loc,2]);
loc=match(Data$SEQN,TCHL[,1]);
Data$TCHL=as.factor(TCHL[loc,2]);
loc=match(Data$SEQN,TCH[,1]);
Data$TCH=as.numeric(TCH[loc,2]);
loc=match(Data$SEQN,THDL[,1]);
Data$THDL=as.numeric(THDL[loc,2]);
loc=match(Data$SEQN,THDL_L[,1]);
Data$THDL_L=as.factor(THDL_L[loc,2]);
loc=match(Data$SEQN,BMI[,1]);
Data$BMI=as.factor(BMI[loc,2]);
loc=match(Data$SEQN,BMICL[,1]);
Data$BMICL=as.numeric(BMICL[loc,2]);
loc=match(Data$SEQN,BMIC[,1]);
Data$BMIC=as.numeric(BMIC[loc,2]);
loc=match(Data$SEQN,Waist[,1]);
Data$Waist=as.numeric(Waist[loc,2]);
loc=match(Data$SEQN,T2D[,1]);
Data$T2D=as.numeric(T2D[loc,2]);
##########################################
### Modeling for factors corelation
##########################################
WaistModel=lm(Waist~BMIC,data=Data);
Data$WaistAdBMI=(Data$Waist-Data$BMIC*WaistModel$coefficients[2]-WaistModel$coefficients[1]);
CholModel=lm(TCH~BMIC,data=Data);
Data$CholAdBMI=(Data$TCH-Data$BMIC*CholModel$coefficients[2]-CholModel$coefficients[1]);
CholModel=lm(TCH~AgeC,data=Data);
Data$CholAdAge=(Data$TCH-Data$AgeC*CholModel$coefficients[2]-CholModel$coefficients[1]);