####################################
##### Processing
####################################
Gender[which(Gender[,2]==1),2]='M';
Gender[which(Gender[,2]==2),2]='F';
Race[which(Race[,2]==1),2]='2Hisp';
Race[which(Race[,2]==2),2]='2Hisp';
Race[which(Race[,2]==3),2]='1NHWhite';
Race[which(Race[,2]==4),2]='3NHBlack';
Race[which(Race[,2]==5),2]='4Other';
BMI=BMIC;
BMI[which(BMIC[,2]<18.5),2]='2Underweight';
BMI[which(BMIC[,2]>=18.5&BMIC[,2]<25),2]='1Normal';
BMI[which(BMIC[,2]>=25&BMIC[,2]<30),2]='3Overweight';
BMI[which(BMIC[,2]>=30),2]='4Obese';
TCHL=TCH;
TCHL[which(TCH[,2]<200),2]='1Normal';
TCHL[which(TCH[,2]>=200&TCH[,2]<240),2]='2High';
TCHL[which(TCH[,2]>=240),2]='3VeryHigh';
TRIGL=TRIG;
TRIGL[which(TRIG[,2]<200),2]='1Normal';
TRIGL[which(TRIG[,2]>=200&TRIG[,2]<500),2]='2High';
TRIGL[which(TRIG[,2]>=500),2]='3VeryHigh';
HDL=TCH[,c(1,3)];
HDLL=HDL;
HDLL[which(HDL[,2]>=40),2]='1Normal';
HDLL[which(HDL[,2]<40),2]='2Low';
CHR=TCH[,c(1,4)];
CHRL=HDL;
CHRL[which(CHR[,2]>=9),2]='3VeryHigh';
CHRL[which(CHR[,2]>=6&CHR[,2]<9),2]='2High';
CHRL[which(CHR[,2]<6),2]='1Normal';
T2D[which(T2D[,2]>2),2]='.';
T2D[which(T2D[,2]==2),2]=0;
#################################
#Matching
#################################
loc=match(Data$SEQN,Age[,1]);
Data$Age=as.factor(round(Age[loc,2]/10));
loc=match(Data$SEQN,AgeM[,1]);
Data$AgeM=as.numeric(as.character(AgeM[loc,2]));
loc=match(Data$SEQN,Age[,1]);
Data$AgeC=as.numeric(as.character(Age[loc,2]));
loc=match(Data$SEQN,Gender[,1]);
Data$Gender=as.factor(Gender[loc,2]);
loc=match(Data$SEQN,Race[,1]);
Data$Race=as.factor(Race[loc,2]);
loc=match(Data$SEQN,TCH[,1]);
Data$TCH=as.numeric(TCH[loc,2]);
loc=match(Data$SEQN,HDL[,1]);
Data$HDL=as.numeric(HDL[loc,2]);
loc=match(Data$SEQN,CHR[,1]);
Data$CHR=as.numeric(CHR[loc,2]);
loc=match(Data$SEQN,TCHL[,1]);
Data$TCHL=as.factor(TCHL[loc,2]);
loc=match(Data$SEQN,HDLL[,1]);
Data$HDLL=as.factor(HDLL[loc,2]);
loc=match(Data$SEQN,CHRL[,1]);
Data$CHRL=as.factor(CHRL[loc,2]);
loc=match(Data$SEQN,BMI[,1]);
Data$BMI=as.factor(BMI[loc,2]);
loc=match(Data$SEQN,BMIC[,1]);
Data$BMIC=as.numeric(BMIC[loc,2]);
#################Add BMI Percentile
BMIAGE<-read.csv ("bmiage.csv", header=T);
loc=match(pmin(pmax(Data$AgeM,24),240)*((Data$Gender=='F')*1000+1*(Data$Gender=='M')),BMIAGE$Agemos2*((BMIAGE$Sex=='F')*1000+1*(BMIAGE$Sex=='M')));
Data$BMIP85=as.numeric(BMIAGE$P85[loc]);
Data$BMIP95=as.numeric(BMIAGE$P95[loc]);
###################################


loc=match(Data$SEQN,Waist[,1]);
Data$Waist=as.numeric(Waist[loc,2]);
loc=match(Data$SEQN,bx$SEQN);
Data$bpmin_max=as.numeric(bx[loc,]$bpmin_max);
loc=match(Data$SEQN,bp$SEQN);
Data$HBP=as.numeric(bp[loc,]$HBP);
Data[which(Data$HBP>2),]$HBP=NA;
Data[which(Data$HBP==2),]$HBP=0;
loc=match(Data$SEQN,bp$SEQN);
Data$RX=as.numeric(bp[loc,]$RX);
loc=match(Data$SEQN,T2D[,1]);
Data$T2D=as.numeric(T2D[loc,2]);
loc=match(Data$SEQN,TRIG[,1]);
Data$TRIG=as.numeric(TRIG[loc,2]);
loc=match(Data$SEQN,TRIGL[,1]);
Data$TRIGL=as.factor(TRIGL[loc,2]);
########################################
###Limiting continous varaibles
#########################################
Choles_ratio_max=13;
Choles_ratio_min=5;
BMI_max=35;
BMI_min=22.5;
TRIG_max=500;
TRIG_min=100;
Data$CHR2=Data$CHR;
Data[which(Data$CHR2>Choles_ratio_max),]$CHR2=Choles_ratio_max;
Data[which(Data$CHR2<Choles_ratio_min),]$CHR2=Choles_ratio_min;
Data$BMIC2=Data$BMIC;
Data[which(Data$BMIC2>BMI_max),]$BMIC2=BMI_max;
Data[which(Data$BMIC2<BMI_min),]$BMIC2=BMI_min;
Data$TRIG2=Data$TRIG;
Data[which(Data$TRIG2>TRIG_max),]$TRIG2=TRIG_max;
Data[which(Data$TRIG2<TRIG_min),]$TRIG2=TRIG_min;
##########################################
### Modeling for factors corelation
##########################################
WaistModel=lm(Waist~BMIC,data=Data);
Data$WaistAdBMI=(Data$Waist-Data$BMIC*WaistModel$coefficients[2]-WaistModel$coefficients[1]);
CholModel=lm(TCH~BMIC,data=Data);
Data$CholAdBMI=(Data$TCH-Data$BMIC*CholModel$coefficients[2]-CholModel$coefficients[1]);
CholModel=lm(TCH~AgeC,data=Data);
Data$CholAdAge=(Data$TCH-Data$AgeC*CholModel$coefficients[2]-CholModel$coefficients[1]);