#!/usr/bin/perl
use strict;
use warnings;
my $fname="s";
    my $fout="$fname\_10";
    my $fbow="$fout.sam";
    my $fin1="$fout\_1.fq";
   my $fin2="$fout\_2.fq";
    system("tar -jxvf $fin1.tar.bz2");
    system("tar -jxvf $fin2.tar.bz2");
    if(open(IN1,$fin1) && open(IN2,$fin2))
    {
        close IN1;
        close IN2;
        system("nohup ./bowtie mom -S --chunkmbs 200 -1 $fin1 -2 $fin2 $fbow >$fout-sum");
        system("rm $fin1");
        system("rm $fin2");
        system("tar -cf $fbow.tar $fbow");
        system("rm $fbow");
        system("bzip2 -zf $fbow.tar");
    }
