#!/usr/bin/perl
## write the matrix X in prep for PCA
### read from transpose of genotype
use strict;
use warnings;



open(FILERUN, ">perlffsfs-RUN");    


for(my $ch=0;$ch<=2;$ch++)
{
    
    my $fname="perl-FFSFS";

    open(FILEOUT, ">$fname-$ch");    
    
    open(FILEIN, "$fname");    
    while (<FILEIN>)
    {
        my $st=$_;
        if($st eq "my \$beg=\"achr\";\n")
        {
            if($ch==0)# auto unfolded
            {

############ thresholds 28
                print FILEOUT "my \$nch=80;\n";
                print FILEOUT "my \$bb=\"28\";\n";
                print FILEOUT "my \$nl=28;\n";
                print FILEOUT "my \$n1=2;\n";
                
                print FILEOUT "my \$tt=36;\n";
                print FILEOUT "my \$t2=8;\n";
                
                print FILEOUT "my \$t1=24;\n";
               print FILEOUT "my \$e=\"f\";\n";
            }
            if($ch==1)# UN+auto unfolded
            {
############ thresholds  UN+auto
                print FILEOUT "my \$bb=\"29\";\n";
                print FILEOUT "my \$nl=29;\n";
                print FILEOUT "my \$n1=2;\n";
                print FILEOUT "my \$nch=80;\n";
                
                print FILEOUT "my \$tt=36;\n";
                print FILEOUT "my \$t2=8;\n";
                print FILEOUT "my \$t1=24;\n";
                print FILEOUT "my \$e=\"f\";\n";
            }
         
            if($ch==2)# auto unfolded
            {
############ UN thresholds
                print FILEOUT "my \$bb=\"UN\";\n";
                print FILEOUT "my \$nl=29;\n";
                print FILEOUT "my \$n1=29;\n";
                print FILEOUT "my \$nch=80;\n";

                print FILEOUT "my \$tt=30;\n";
                print FILEOUT "my \$t2=6;\n";
             
                
                print FILEOUT "my \$t1=20;\n";
                print FILEOUT "my \$e=\"f\";\n";
            }
        }
        print FILEOUT $st;
        
      
    }
    my $tt="fauto";
    if($ch==1)
    {$tt="fUNauto";}
    if($ch==2)
    {$tt="fUN";}
       
    print FILERUN "nohup ./$fname-$ch  >$tt &\n";
    close(FILEIN);
    close(FILEOUT)
        
}
close(FILERUN);
